type: pipeline
pipes:
  - name: db_schema_indexing
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: historical_question_indexing
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: table_description_indexing
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: db_schema_retrieval
    llm: litellm_llm.default
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: historical_question_retrieval
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: sql_generation
    llm: litellm_llm.default
    engine: analytics_ui
    document_store: qdrant
  - name: sql_correction
    llm: litellm_llm.default
    engine: analytics_ui
    document_store: qdrant
  - name: followup_sql_generation
    llm: litellm_llm.default
    engine: analytics_ui
    document_store: qdrant
  - name: sql_answer
    llm: {{LLM_SQL_ANSWER}}
  - name: semantics_description
    llm: litellm_llm.default
  - name: relationship_recommendation
    llm: litellm_llm.default
    engine: analytics_ui
  - name: question_recommendation
    llm: litellm_llm.default
  - name: question_recommendation_db_schema_retrieval
    llm: litellm_llm.default
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: question_recommendation_sql_generation
    llm: litellm_llm.default
    engine: analytics_ui
    document_store: qdrant
  - name: chart_generation
    llm: {{LLM_CHART_GENERATION}}
  - name: chart_adjustment
    llm: {{LLM_CHART_ADJUSTMENT}}
  - name: intent_classification
    llm: litellm_llm.default
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: misleading_assistance
    llm: litellm_llm.default
  - name: data_assistance
    llm: {{LLM_DATA_ASSISTANCE}}
  - name: sql_pairs_preparation
    document_store: qdrant
    embedder: litellm_embedder.default
    llm: litellm_llm.default
  - name: sql_pairs_indexing
    document_store: qdrant
    embedder: litellm_embedder.default
  - name: sql_pairs_retrieval
    document_store: qdrant
    embedder: litellm_embedder.default
    llm: litellm_llm.default
  - name: preprocess_sql_data
    llm: litellm_llm.default
  - name: sql_executor
    engine: analytics_ui
  - name: user_guide_assistance
    llm: litellm_llm.default
  - name: sql_question_generation
    llm: litellm_llm.default
  - name: sql_generation_reasoning
    llm: {{LLM_SQL_GENERATION_REASONING}}
  - name: followup_sql_generation_reasoning
    llm: {{LLM_FOLLOWUP_SQL_GENERATION_REASONING}}
  - name: sql_regeneration
    llm: litellm_llm.default
    engine: analytics_ui
  - name: instructions_indexing
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: instructions_retrieval
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: sql_functions_retrieval
    engine: analytics_ibis
    document_store: qdrant
  - name: project_meta_indexing
    document_store: qdrant
  - name: sql_tables_extraction
    llm: litellm_llm.default
  - name: sql_diagnosis
    llm: litellm_llm.default
